import {bindings} from '../../../server';
import {availableFrom,ensureStudentPeriodSessions,requirePortalStudent} from '../_auth';
const scheduleLabel="(CASE s.day WHEN 1 THEN 'Lunes' WHEN 2 THEN 'Martes' WHEN 3 THEN 'Miércoles' WHEN 4 THEN 'Jueves' WHEN 5 THEN 'Viernes' WHEN 6 THEN 'Sábado' ELSE 'Domingo' END || ' ' || s.start || '-' || s.end)";
export async function GET(request:Request){const student=await requirePortalStudent(request);if(student instanceof Response)return student;const url=new URL(request.url),period=(url.searchParams.get('period')||new Date().toISOString().slice(0,7));const db=bindings().DB;await ensureStudentPeriodSessions(student.id,period);const {results:myClasses}=await db.prepare(`SELECT cs.id,cs.date,s.start,s.end,s.capacity,${scheduleLabel} AS schedule_label,st.name AS teacher_name,ar.status AS attendance_status,ar.credit_id
FROM class_sessions cs JOIN schedules s ON s.id=cs.schedule_id JOIN student_schedules ss ON ss.schedule_id=s.id LEFT JOIN staff_members st ON st.id=s.teacher_id LEFT JOIN attendance_records ar ON ar.session_id=cs.id AND ar.student_id=ss.student_id
WHERE ss.student_id=? AND cs.date LIKE ? AND cs.status!='cancelled' ORDER BY cs.date,s.start`).bind(student.id,period+'%').all();
const {results:credits}=await db.prepare("SELECT * FROM recovery_credits WHERE student_id=? AND status IN ('available','reserved') ORDER BY expires_at").bind(student.id).all();
const {results:bookings}=await db.prepare(`SELECT rb.*,cs.date AS class_date,${scheduleLabel} AS schedule_label FROM recovery_bookings rb JOIN class_sessions cs ON cs.id=rb.session_id JOIN schedules s ON s.id=cs.schedule_id WHERE rb.student_id=? AND rb.status!='cancelled' ORDER BY cs.date`).bind(student.id).all();
const {results:classes}=await db.prepare(`SELECT cs.id,cs.date,s.start,s.end,s.capacity,${scheduleLabel} AS schedule_label,st.name AS teacher_name,
(SELECT COUNT(*) FROM student_schedules ss JOIN students stu ON stu.id=ss.student_id WHERE ss.schedule_id=s.id AND stu.status!='inactive') AS fixed_count,
(SELECT COUNT(*) FROM attendance_records ar WHERE ar.session_id=cs.id AND ar.status IN ('notice','absent','cancelled')) AS absent_count,
(SELECT COUNT(*) FROM recovery_bookings rb WHERE rb.session_id=cs.id AND rb.status!='cancelled') AS recovery_count
FROM class_sessions cs JOIN schedules s ON s.id=cs.schedule_id LEFT JOIN staff_members st ON st.id=s.teacher_id WHERE cs.date LIKE ? AND cs.status!='cancelled' ORDER BY cs.date,s.start`).bind(period+'%').all<any>();
return Response.json({student,period,myClasses,credits,bookings,recoveryClasses:classes.map(c=>({...c,available:availableFrom(c)}))},{headers:{'Cache-Control':'no-store'}})}
export async function PUT(request:Request){const student=await requirePortalStudent(request);if(student instanceof Response)return student;try{const p=await request.json() as {name?:string;contact?:string;instagram?:string;family_group?:string;notes?:string};const name=(p.name||'').trim().slice(0,120),contact=(p.contact||'').trim().slice(0,80),instagram=(p.instagram||'').trim().slice(0,80),family_group=(p.family_group||'').trim().slice(0,120),notes=(p.notes||'').trim().slice(0,1200);if(!name)return Response.json({error:'Completá tu nombre.'},{status:400});await bindings().DB.prepare('UPDATE students SET name=?,contact=?,instagram=?,family_group=?,notes=?,updated_at=? WHERE id=?').bind(name,contact,instagram,family_group,notes,new Date().toISOString(),student.id).run();return Response.json({ok:true})}catch{return Response.json({error:'No pudimos actualizar tu ficha.'},{status:500})}}
