'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {expenseCategoryLabels,paymentStatusLabels,staffPaymentKindLabels,studentPaymentTypeLabels,type ExpenseCategory,type PaymentStatus,type Schedule,type StaffMember,type StaffPayment,type StaffPaymentKind,type Student,type StudentPayment,type StudentPaymentType,type WorkLog,type WorkshopExpense} from '../shared';
const month=()=>new Date().toISOString().slice(0,7),date=()=>new Date().toISOString().slice(0,10),money=(n:number)=>'$'+(n/100).toLocaleString('es-AR'),cents=(v:string)=>Math.round(Number(v||0)*100),pesos=(n:number|null|undefined)=>n?String(Math.round(n/100)):'';
const blankPay:StudentPayment={id:'',student_id:'',schedule_id:'',type:'monthly',status:'pending',period:month(),amount:0,paid_amount:0,paid_at:'',method:'',notes:'',created_at:'',updated_at:''};
const blankExp:WorkshopExpense={id:'',category:'materials',description:'',amount:0,expense_date:date(),period:month(),method:'',notes:'',created_at:'',updated_at:''};
const blankLog:WorkLog={id:'',staff_id:'',work_date:date(),start_time:'09:00',end_time:'13:00',hours:4,hourly_rate:null,status:'pending',notes:'',created_at:'',updated_at:''};
const blankStaffPay:StaffPayment={id:'',staff_id:'',kind:'teacher_share',status:'pending',period:month(),amount:0,paid_at:'',method:'',notes:'',created_at:'',updated_at:''};
export default function FinanceEditor(){const[students,setStudents]=useState<Student[]>([]),[staff,setStaff]=useState<StaffMember[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[studentPayments,setStudentPayments]=useState<StudentPayment[]>([]),[expenses,setExpenses]=useState<WorkshopExpense[]>([]),[logs,setLogs]=useState<WorkLog[]>([]),[staffPayments,setStaffPayments]=useState<StaffPayment[]>([]),[pay,setPay]=useState({...blankPay}),[exp,setExp]=useState({...blankExp}),[log,setLog]=useState({...blankLog}),[sp,setSp]=useState({...blankStaffPay}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
async function load(){setLoading(true);try{const[st,tf,sc,py,ex,wl,sfp]=await Promise.all([fetch('/api/admin/students'),fetch('/api/admin/staff'),fetch('/api/admin/schedules'),fetch('/api/admin/student-payments'),fetch('/api/admin/expenses'),fetch('/api/admin/work-logs'),fetch('/api/admin/staff-payments')]);const dst=await st.json(),dtf=await tf.json(),dsc=await sc.json(),dpy=await py.json(),dex=await ex.json(),dwl=await wl.json(),dsfp=await sfp.json();for(const [r,d] of [[st,dst],[tf,dtf],[sc,dsc],[py,dpy],[ex,dex],[wl,dwl],[sfp,dsfp]] as const)if(!r.ok)throw Error(d.error);setStudents(dst.students);setStaff(dtf.staff);setSchedules(dsc.schedules);setStudentPayments(dpy.payments);setExpenses(dex.expenses);setLogs(dwl.logs);setStaffPayments(dsfp.payments)}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos cargar economía.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
const scheduleLabel=(s:Schedule)=>`${s.start}-${s.end} · ${s.teacher_name||'sin profe'}`;async function post(url:string,body:unknown,ok:string){setBusy(true);setError(false);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage(ok);await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos guardar.')}finally{setBusy(false)}}
async function submitPay(e:FormEvent){e.preventDefault();await post('/api/admin/student-payments',pay,'Cobro guardado.');setPay({...blankPay})}
async function submitExp(e:FormEvent){e.preventDefault();await post('/api/admin/expenses',exp,'Gasto guardado.');setExp({...blankExp})}
async function submitLog(e:FormEvent){e.preventDefault();await post('/api/admin/work-logs',log,'Horas guardadas.');setLog({...blankLog})}
async function submitStaffPay(e:FormEvent){e.preventDefault();await post('/api/admin/staff-payments',sp,'Pago al equipo guardado.');setSp({...blankStaffPay})}
const current=month(),income=studentPayments.filter(p=>p.period===current).reduce((a,p)=>a+p.paid_amount,0),pending=studentPayments.filter(p=>p.period===current&&p.status!=='paid').reduce((a,p)=>a+(p.amount-p.paid_amount),0),spent=expenses.filter(e=>e.period===current).reduce((a,e)=>a+e.amount,0)+staffPayments.filter(p=>p.period===current&&p.status==='paid').reduce((a,p)=>a+p.amount,0);
return <section className="admin-section"><div className="admin-section-head"><div><p className="eyebrow">MI TALLER</p><h2>Economía</h2><p>Cargá cobros, gastos, horas trabajadas y pagos al equipo.</p></div></div><div className="feedback-slot" aria-live="polite">{message&&<p className={'feedback'+(error?' error':'')} role={error?'alert':'status'}>{message}</p>}</div>
<section className="finance-summary"><article><span>Cobrado este mes</span><strong>{money(income)}</strong></article><article><span>Pendiente de cobro</span><strong>{money(pending)}</strong></article><article><span>Gastos + pagos</span><strong>{money(spent)}</strong></article><article><span>Balance estimado</span><strong>{money(income-spent)}</strong></article></section>
<div className="admin-workshop-grid finance-grid">
<form className="admin-form compact-form" onSubmit={submitPay}><div className="wide editor-heading"><div><p className="eyebrow">COBROS</p><h3>Pago alumna</h3></div></div><label>Alumna<select required value={pay.student_id} onChange={e=>setPay({...pay,student_id:e.target.value})}><option value="">Elegí</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Tipo<select value={pay.type} onChange={e=>setPay({...pay,type:e.target.value as StudentPaymentType})}>{Object.entries(studentPaymentTypeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Mes<input type="month" value={pay.period} onChange={e=>setPay({...pay,period:e.target.value})}/></label><label>Estado<select value={pay.status} onChange={e=>setPay({...pay,status:e.target.value as PaymentStatus})}>{Object.entries(paymentStatusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Importe $<input type="number" min="0" value={pesos(pay.amount)} onChange={e=>setPay({...pay,amount:cents(e.target.value)})}/></label><label>Pagado $<input type="number" min="0" value={pesos(pay.paid_amount)} onChange={e=>setPay({...pay,paid_amount:cents(e.target.value)})}/></label><label>Fecha pago<input type="date" value={pay.paid_at} onChange={e=>setPay({...pay,paid_at:e.target.value})}/></label><label>Medio<input value={pay.method} onChange={e=>setPay({...pay,method:e.target.value})}/></label><label className="wide">Horario<select value={pay.schedule_id} onChange={e=>setPay({...pay,schedule_id:e.target.value})}><option value="">Sin horario</option>{schedules.map(s=><option key={s.id} value={s.id}>{scheduleLabel(s)}</option>)}</select></label><label className="wide">Notas<input value={pay.notes} onChange={e=>setPay({...pay,notes:e.target.value})}/></label><button className="button wide" disabled={busy}>Guardar cobro</button></form>
<form className="admin-form compact-form" onSubmit={submitExp}><div className="wide editor-heading"><div><p className="eyebrow">GASTOS</p><h3>Gasto taller</h3></div></div><label>Categoría<select value={exp.category} onChange={e=>setExp({...exp,category:e.target.value as ExpenseCategory})}>{Object.entries(expenseCategoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Mes<input type="month" value={exp.period} onChange={e=>setExp({...exp,period:e.target.value})}/></label><label className="wide">Descripción<input required value={exp.description} onChange={e=>setExp({...exp,description:e.target.value})}/></label><label>Importe $<input type="number" min="0" value={pesos(exp.amount)} onChange={e=>setExp({...exp,amount:cents(e.target.value)})}/></label><label>Fecha<input type="date" value={exp.expense_date} onChange={e=>setExp({...exp,expense_date:e.target.value})}/></label><label>Medio<input value={exp.method} onChange={e=>setExp({...exp,method:e.target.value})}/></label><label className="wide">Notas<input value={exp.notes} onChange={e=>setExp({...exp,notes:e.target.value})}/></label><button className="button wide" disabled={busy}>Guardar gasto</button></form>
<form className="admin-form compact-form" onSubmit={submitLog}><div className="wide editor-heading"><div><p className="eyebrow">HORAS</p><h3>Horas equipo</h3></div></div><label className="wide">Persona<select required value={log.staff_id} onChange={e=>setLog({...log,staff_id:e.target.value})}><option value="">Elegí</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Fecha<input type="date" value={log.work_date} onChange={e=>setLog({...log,work_date:e.target.value})}/></label><label>Desde<input type="time" value={log.start_time} onChange={e=>setLog({...log,start_time:e.target.value})}/></label><label>Hasta<input type="time" value={log.end_time} onChange={e=>setLog({...log,end_time:e.target.value})}/></label><label>Horas<input type="number" step=".25" min="0" value={log.hours} onChange={e=>setLog({...log,hours:Number(e.target.value)})}/></label><label>Valor hora $<input type="number" min="0" value={pesos(log.hourly_rate)} onChange={e=>setLog({...log,hourly_rate:e.target.value?cents(e.target.value):null})}/></label><label>Estado<select value={log.status} onChange={e=>setLog({...log,status:e.target.value as PaymentStatus})}>{Object.entries(paymentStatusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="wide">Notas<input value={log.notes} onChange={e=>setLog({...log,notes:e.target.value})}/></label><button className="button wide" disabled={busy}>Guardar horas</button></form>
<form className="admin-form compact-form" onSubmit={submitStaffPay}><div className="wide editor-heading"><div><p className="eyebrow">EQUIPO</p><h3>Pago / liquidación</h3></div></div><label>Persona<select required value={sp.staff_id} onChange={e=>setSp({...sp,staff_id:e.target.value})}><option value="">Elegí</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Tipo<select value={sp.kind} onChange={e=>setSp({...sp,kind:e.target.value as StaffPaymentKind})}>{Object.entries(staffPaymentKindLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Mes<input type="month" value={sp.period} onChange={e=>setSp({...sp,period:e.target.value})}/></label><label>Estado<select value={sp.status} onChange={e=>setSp({...sp,status:e.target.value as PaymentStatus})}>{Object.entries(paymentStatusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Importe $<input type="number" min="0" value={pesos(sp.amount)} onChange={e=>setSp({...sp,amount:cents(e.target.value)})}/></label><label>Fecha pago<input type="date" value={sp.paid_at} onChange={e=>setSp({...sp,paid_at:e.target.value})}/></label><label>Medio<input value={sp.method} onChange={e=>setSp({...sp,method:e.target.value})}/></label><label className="wide">Notas<input placeholder="Ej.: 30% sobre cobros del horario de viernes" value={sp.notes} onChange={e=>setSp({...sp,notes:e.target.value})}/></label><button className="button wide" disabled={busy}>Guardar pago</button></form>
</div>
<div className="admin-workshop-lists">{loading?<div className="admin-loading" role="status"><span/>Actualizando economía…</div>:<><section><h3>Últimos cobros</h3>{studentPayments.slice(0,6).map(p=><article key={p.id}><strong>{p.student_name}</strong><p>{studentPaymentTypeLabels[p.type]} · {paymentStatusLabels[p.status]} · {money(p.paid_amount)} / {money(p.amount)}</p></article>)}</section><section><h3>Últimos gastos</h3>{expenses.slice(0,6).map(e=><article key={e.id}><strong>{e.description}</strong><p>{expenseCategoryLabels[e.category]} · {money(e.amount)}</p></article>)}</section><section><h3>Horas y pagos</h3>{[...logs.slice(0,3).map(l=>({id:l.id,title:l.staff_name||'',text:`${l.hours} hs · ${paymentStatusLabels[l.status]}`})),...staffPayments.slice(0,3).map(p=>({id:p.id,title:p.staff_name||'',text:`${staffPaymentKindLabels[p.kind]} · ${money(p.amount)}`}))].map(i=><article key={i.id}><strong>{i.title}</strong><p>{i.text}</p></article>)}</section></>}</div></section>}
