'use client';
import {useEffect,useMemo,useState} from 'react';
import {attendanceStatusLabels,creditStatusLabels,paymentStatusLabels,staffPaymentKindLabels,type AttendanceRecord,type RecoveryCredit,type Schedule,type StaffMember,type StaffPayment,type StudentPayment,type WaitlistEntry,type WorkLog,type WorkshopExpense} from '../shared';
const month=()=>new Date().toISOString().slice(0,7),money=(n:number)=>'$'+(n/100).toLocaleString('es-AR'),csv=(rows:Record<string,unknown>[])=>{const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];return [keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n')},download=(name:string,rows:Record<string,unknown>[])=>{const blob=new Blob(['\ufeff'+csv(rows)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
export default function ReportsEditor(){const[period,setPeriod]=useState(month()),[studentPayments,setStudentPayments]=useState<StudentPayment[]>([]),[expenses,setExpenses]=useState<WorkshopExpense[]>([]),[staffPayments,setStaffPayments]=useState<StaffPayment[]>([]),[logs,setLogs]=useState<WorkLog[]>([]),[attendance,setAttendance]=useState<AttendanceRecord[]>([]),[credits,setCredits]=useState<RecoveryCredit[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[staff,setStaff]=useState<StaffMember[]>([]),[waitlist,setWaitlist]=useState<WaitlistEntry[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
async function load(){setLoading(true);try{const urls=['/api/admin/student-payments','/api/admin/expenses','/api/admin/staff-payments','/api/admin/work-logs','/api/admin/attendance','/api/admin/credits','/api/admin/schedules','/api/admin/staff','/api/admin/waitlist'];const data=await Promise.all(urls.map(async u=>{const r=await fetch(u);const d=await r.json();if(!r.ok)throw Error(d.error);return d}));setStudentPayments(data[0].payments);setExpenses(data[1].expenses);setStaffPayments(data[2].payments);setLogs(data[3].logs);setAttendance(data[4].attendance);setCredits(data[5].credits);setSchedules(data[6].schedules);setStaff(data[7].staff);setWaitlist(data[8].waitlist)}catch(e){setMessage(e instanceof Error?e.message:'No pudimos cargar reportes.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
const report=useMemo(()=>{const pays=studentPayments.filter(p=>p.period===period),exps=expenses.filter(e=>e.period===period),team=staffPayments.filter(p=>p.period===period),work=logs.filter(l=>l.work_date.startsWith(period));const income=pays.reduce((a,p)=>a+p.paid_amount,0),expected=pays.reduce((a,p)=>a+p.amount,0),pending=pays.reduce((a,p)=>a+Math.max(0,p.amount-p.paid_amount),0),spent=exps.reduce((a,e)=>a+e.amount,0)+team.filter(p=>p.status==='paid').reduce((a,p)=>a+p.amount,0);const teacherRows=staff.filter(s=>s.kind==='teacher').map(t=>{const teacherSchedules=schedules.filter(s=>s.teacher_id===t.id),scheduleIds=new Set(teacherSchedules.map(s=>s.id)),teacherPays=pays.filter(p=>scheduleIds.has(p.schedule_id)),collected=teacherPays.reduce((a,p)=>a+p.paid_amount,0),share=Math.round(collected*((t.percentage??30)/100));return {profe:t.name,horarios:teacherSchedules.length,alumnas:teacherSchedules.reduce((a,s)=>a+(s.student_count||0),0),cobrado:collected,liquidar:share,porcentaje:t.percentage??30}});return {pays,exps,team,work,income,expected,pending,spent,balance:income-spent,teacherRows}},[period,studentPayments,expenses,staffPayments,logs,staff,schedules]);
const attendanceRows=attendance.map(a=>({alumna:a.student_name||'',estado:attendanceStatusLabels[a.status],genero_credito:a.credit_id?'sí':'no',uso_credito:a.recovery_credit_used_id?'sí':'no',notas:a.notes}));
const exportBalance=()=>download(`balance-${period}.csv`,[{periodo:period,ingresos:report.income,pendiente:report.pending,gastos:report.spent,balance:report.balance}]);
const exportPayments=()=>download(`pagos-${period}.csv`,report.pays.map(p=>({alumna:p.student_name,tipo:p.type,estado:paymentStatusLabels[p.status],importe:p.amount,pagado:p.paid_amount,mes:p.period,medio:p.method})));
const exportTeachers=()=>download(`profes-${period}.csv`,report.teacherRows);
const exportAttendance=()=>download(`asistencias-${period}.csv`,attendanceRows);
const exportStaffPayments=()=>download(`liquidaciones-${period}.csv`,report.team.map(p=>({persona:p.staff_name,tipo:staffPaymentKindLabels[p.kind],estado:paymentStatusLabels[p.status],importe:p.amount,mes:p.period,medio:p.method})));
const exportHours=()=>download(`horas-${period}.csv`,report.work.map(l=>({persona:l.staff_name,fecha:l.work_date,desde:l.start_time,hasta:l.end_time,horas:l.hours,estado:paymentStatusLabels[l.status]})));
const exportCredits=()=>download(`recuperaciones-${period}.csv`,credits.map(c=>({alumna:c.student_name,estado:creditStatusLabels[c.status],vence:c.expires_at,notas:c.notes})));
return <section className="admin-section"><div className="admin-section-head"><div><p className="eyebrow">MI TALLER</p><h2>Reportes y exportables</h2><p>Revisá balance mensual, profes, asistencia y descargá archivos compatibles con Excel.</p></div><label className="report-month">Mes<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label></div>{message&&<p className="feedback error">{message}</p>}
<section className="finance-summary reports-summary"><article><span>Ingresos cobrados</span><strong>{money(report.income)}</strong></article><article><span>Pendiente de cobro</span><strong>{money(report.pending)}</strong></article><article><span>Gastos + equipo</span><strong>{money(report.spent)}</strong></article><article><span>Ganancia estimada</span><strong>{money(report.balance)}</strong></article></section>
<div className="admin-workshop-lists reports-lists">{loading?<div className="admin-loading" role="status"><span/>Actualizando reportes…</div>:<><section><h3>Por profe</h3>{report.teacherRows.map(r=><article key={r.profe}><strong>{r.profe}</strong><p>{r.horarios} horario(s) · {r.alumnas} alumna(s) · cobrado {money(r.cobrado)} · liquidar {money(r.liquidar)}</p></article>)}</section><section><h3>Asistencia</h3><article><strong>Presentes</strong><p>{attendance.filter(a=>a.status==='present').length}</p></article><article><strong>Ausencias con aviso</strong><p>{attendance.filter(a=>a.status==='notice').length}</p></article><article><strong>Recuperaciones</strong><p>{credits.filter(c=>c.status==='available').length} pendientes · {credits.filter(c=>c.status==='used').length} usadas</p></article></section><section><h3>Interesadas</h3>{waitlist.slice(0,5).map(w=><article key={w.id}><strong>{w.student_name}</strong><p>{w.schedule_label} · {w.status}</p></article>)}</section></>}</div>
<section className="export-panel"><h3>Exportables CSV / Excel</h3><div className="workshop-actions export-actions"><button onClick={exportBalance}>Balance mensual</button><button onClick={exportPayments}>Pagos alumnas</button><button onClick={exportTeachers}>Reporte profes</button><button onClick={exportAttendance}>Asistencias</button><button onClick={exportStaffPayments}>Liquidaciones</button><button onClick={exportHours}>Horas trabajadas</button><button onClick={exportCredits}>Recuperaciones</button></div></section></section>}
