'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {dayLabels,scheduleStatusLabels,type Schedule,type ScheduleStatus} from '../shared';
const blank:Schedule={id:'',day:1,start:'10:00',end:'12:00',status:'forming',note:'',published:1,sort:0};
export default function ScheduleEditor(){const[items,setItems]=useState<Schedule[]>([]),[draft,setDraft]=useState<Schedule>({...blank}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[dirty,setDirty]=useState(false);
async function load(){setLoading(true);try{const r=await fetch('/api/admin/schedules');const data=await r.json() as {error?:string;schedules:Schedule[]};if(!r.ok)throw Error(data.error);setItems(data.schedules)}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos cargar los horarios.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
function update<K extends keyof Schedule>(key:K,value:Schedule[K]){setDraft(d=>({...d,[key]:value}));setDirty(true)}function reset(){setDraft({...blank});setDirty(false);setMessage('')};function edit(item:Schedule){if(dirty&&!confirm('Tenés cambios sin guardar. ¿Querés descartarlos?'))return;setDraft({...item});setDirty(false);setMessage('');document.getElementById('schedule-form')?.scrollIntoView({behavior:'smooth'})}
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(false);setMessage('');try{const r=await fetch('/api/admin/schedules',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const data=await r.json() as {error?:string;id:string};if(!r.ok)throw Error(data.error);setDraft(d=>({...d,id:data.id}));setDirty(false);setMessage(draft.published?'Horario guardado y visible.':'Horario guardado como borrador.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos guardar el horario.')}finally{setBusy(false)}}
async function remove(item:Schedule){if(!confirm(`¿Eliminar el horario del ${dayLabels[item.day]} de ${item.start} a ${item.end}?`))return;setBusy(true);setError(false);try{const r=await fetch('/api/admin/schedules?id='+encodeURIComponent(item.id),{method:'DELETE'});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);if(draft.id===item.id)reset();setMessage('Horario eliminado.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos eliminar el horario.')}finally{setBusy(false)}}
return <section className="admin-section"><div className="admin-section-head"><div><p className="eyebrow">CLASES</p><h2>Horarios y cupos</h2><p>Publicá la grilla y actualizá el estado de cada grupo.</p></div><button className="button" onClick={reset} disabled={busy}>+ Nuevo horario</button></div><div className="feedback-slot" aria-live="polite">{message&&<p className={'feedback'+(error?' error':'')} role={error?'alert':'status'}>{message}</p>}</div>
<form id="schedule-form" className="admin-form schedule-form" onSubmit={submit}><div className="wide editor-heading"><div><p className="eyebrow">{draft.id?'EDITANDO':'CREANDO'}</p><h3>{draft.id?`${dayLabels[draft.day]} · ${draft.start}`:'Nuevo horario'}</h3></div>{draft.id&&<button className="text-link" type="button" onClick={reset}>Cancelar edición</button>}</div><label>Día<select value={draft.day} onChange={e=>update('day',Number(e.target.value))}>{dayLabels.slice(1,7).map((label,i)=><option value={i+1} key={label}>{label}</option>)}</select></label><label>Estado<select value={draft.status} onChange={e=>update('status',e.target.value as ScheduleStatus)}>{Object.entries(scheduleStatusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Desde<input type="time" required value={draft.start} onChange={e=>update('start',e.target.value)}/></label><label>Hasta<input type="time" required value={draft.end} onChange={e=>update('end',e.target.value)}/></label><label className="wide">Nota opcional<input maxLength={160} placeholder="Ej.: Nivel inicial · 2 horas semanales" value={draft.note} onChange={e=>update('note',e.target.value)}/></label><label>Orden dentro del día<input type="number" min="0" max="9999" value={draft.sort} onChange={e=>update('sort',Number(e.target.value))}/></label><label className="checkbox"><input type="checkbox" checked={draft.published===1} onChange={e=>update('published',e.target.checked?1:0)}/>Mostrar en el sitio</label><div className="wide form-actions save-actions"><button className="button" type="submit" disabled={busy||!dirty}>{busy?'Guardando…':'Guardar horario'}</button>{dirty&&<span className="note unsaved">Cambios sin guardar</span>}</div></form>
<h3 className="admin-list-title">Grilla cargada</h3>{loading?<div className="admin-loading" role="status"><span/>Actualizando horarios…</div>:!items.length?<p>Todavía no cargaste horarios.</p>:<div className="admin-schedule-list">{items.map(item=><article key={item.id}><div><strong>{dayLabels[item.day]} · {item.start} a {item.end}</strong><p><span className={'schedule-admin-status status-'+item.status}>{scheduleStatusLabels[item.status]}</span> · {item.published?'Visible':'Borrador'}{item.note?' · '+item.note:''}</p></div><div><button className="button small secondary" onClick={()=>edit(item)} disabled={busy}>Editar</button><button className="text-link danger" onClick={()=>void remove(item)} disabled={busy}>Eliminar</button></div></article>)}</div>}</section>}
