'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {payModeLabels,staffKindLabels,type PayMode,type StaffKind,type StaffMember} from '../shared';
const blank:StaffMember={id:'',name:'',email:'',phone:'',kind:'teacher',status:'active',pay_mode:'percentage',hourly_rate:null,monthly_amount:null,percentage:30,notes:'',created_at:'',updated_at:''};
const pesos=(v:number|null)=>v===null?'':String(Math.round(v/100));
export default function StaffEditor(){const[items,setItems]=useState<StaffMember[]>([]),[draft,setDraft]=useState<StaffMember>({...blank}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[dirty,setDirty]=useState(false);
async function load(){setLoading(true);try{const r=await fetch('/api/admin/staff');const data=await r.json() as {error?:string;staff:StaffMember[]};if(!r.ok)throw Error(data.error);setItems(data.staff)}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos cargar el equipo.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
function update<K extends keyof StaffMember>(key:K,value:StaffMember[K]){setDraft(d=>({...d,[key]:value}));setDirty(true)}function reset(){setDraft({...blank});setDirty(false);setMessage('')}function edit(item:StaffMember){if(dirty&&!confirm('Tenés cambios sin guardar. ¿Querés descartarlos?'))return;setDraft({...item});setDirty(false);setMessage('');document.getElementById('staff-form')?.scrollIntoView({behavior:'smooth'})}
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(false);setMessage('');try{const r=await fetch('/api/admin/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const data=await r.json() as {error?:string;id:string};if(!r.ok)throw Error(data.error);setDraft(d=>({...d,id:data.id}));setDirty(false);setMessage('Ficha guardada.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos guardar la ficha.')}finally{setBusy(false)}}
async function remove(item:StaffMember){if(!confirm(`¿Eliminar la ficha de ${item.name}?`))return;setBusy(true);setError(false);try{const r=await fetch('/api/admin/staff?id='+encodeURIComponent(item.id),{method:'DELETE'});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);if(draft.id===item.id)reset();setMessage('Ficha eliminada.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos eliminar la ficha.')}finally{setBusy(false)}}
return <section className="admin-section"><div className="admin-section-head"><div><p className="eyebrow">MI TALLER</p><h2>Profes y equipo</h2><p>Registrá profes, asistencia, limpieza, CM y otras personas del espacio.</p></div><button className="button" onClick={reset} disabled={busy}>+ Nueva ficha</button></div><div className="feedback-slot" aria-live="polite">{message&&<p className={'feedback'+(error?' error':'')} role={error?'alert':'status'}>{message}</p>}</div>
<form id="staff-form" className="admin-form team-form" onSubmit={submit}><div className="wide editor-heading"><div><p className="eyebrow">{draft.id?'EDITANDO':'CREANDO'}</p><h3>{draft.id?draft.name:'Nueva persona'}</h3></div>{draft.id&&<button className="text-link" type="button" onClick={reset}>Cancelar edición</button>}</div><label>Nombre<input required maxLength={120} value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Tipo<select value={draft.kind} onChange={e=>update('kind',e.target.value as StaffKind)}>{Object.entries(staffKindLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Mail<input type="email" maxLength={180} value={draft.email} onChange={e=>update('email',e.target.value)}/></label><label>Teléfono<input maxLength={80} value={draft.phone} onChange={e=>update('phone',e.target.value)}/></label><label>Estado<select value={draft.status} onChange={e=>update('status',e.target.value as StaffMember['status'])}><option value="active">Activa</option><option value="paused">Pausada</option><option value="inactive">Inactiva</option></select></label><label>Modalidad de pago<select value={draft.pay_mode} onChange={e=>update('pay_mode',e.target.value as PayMode)}>{Object.entries(payModeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Porcentaje<input type="number" min="0" max="100" value={draft.percentage??''} onChange={e=>update('percentage',e.target.value===''?null:Number(e.target.value))}/></label><label>Valor hora $<input type="number" min="0" value={pesos(draft.hourly_rate)} onChange={e=>update('hourly_rate',e.target.value===''?null:Math.round(Number(e.target.value)*100))}/></label><label>Monto mensual $<input type="number" min="0" value={pesos(draft.monthly_amount)} onChange={e=>update('monthly_amount',e.target.value===''?null:Math.round(Number(e.target.value)*100))}/></label><label className="wide">Notas<textarea rows={4} maxLength={1200} value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label><div className="wide form-actions save-actions"><button className="button" type="submit" disabled={busy||!dirty}>{busy?'Guardando…':'Guardar ficha'}</button>{dirty&&<span className="note unsaved">Cambios sin guardar</span>}</div></form>
<h3 className="admin-list-title">Fichas cargadas</h3>{loading?<div className="admin-loading" role="status"><span/>Actualizando equipo…</div>:!items.length?<p>Todavía no cargaste fichas del equipo.</p>:<div className="admin-schedule-list">{items.map(item=><article key={item.id}><div><strong>{item.name}</strong><p>{staffKindLabels[item.kind]} · {item.status==='active'?'Activa':item.status==='paused'?'Pausada':'Inactiva'} · {payModeLabels[item.pay_mode]}{item.percentage!==null?' · '+item.percentage+'%':''}</p></div><div><button className="button small secondary" onClick={()=>edit(item)} disabled={busy}>Editar</button><button className="text-link danger" onClick={()=>void remove(item)} disabled={busy}>Eliminar</button></div></article>)}</div>}</section>}
