'use client';
import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {dayLabels,studentStatusLabels,type Schedule,type Student,type StudentStatus} from '../shared';
const blank:Student={id:'',name:'',contact:'',email:'',instagram:'',family_group:'',status:'active',notes:'',schedule_ids:'',created_at:'',updated_at:''};
export default function StudentEditor(){const[items,setItems]=useState<Student[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[draft,setDraft]=useState<Student>({...blank}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[dirty,setDirty]=useState(false);
async function load(){setLoading(true);try{const[rs,rg]=await Promise.all([fetch('/api/admin/students'),fetch('/api/admin/schedules')]);const ds=await rs.json() as {error?:string;students:Student[]};const dg=await rg.json() as {error?:string;schedules:Schedule[]};if(!rs.ok)throw Error(ds.error);if(!rg.ok)throw Error(dg.error);setItems(ds.students);setSchedules(dg.schedules)}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos cargar alumnas.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
const selected=useMemo(()=>new Set((draft.schedule_ids||'').split(',').filter(Boolean)),[draft.schedule_ids]);const label=(s:Schedule)=>`${dayLabels[s.day]} ${s.start}-${s.end}${s.teacher_name?' · '+s.teacher_name:''}`;
function update<K extends keyof Student>(key:K,value:Student[K]){setDraft(d=>({...d,[key]:value}));setDirty(true)}function toggle(id:string){const next=new Set(selected);next.has(id)?next.delete(id):next.add(id);update('schedule_ids',[...next].join(','))}function reset(){setDraft({...blank});setDirty(false);setMessage('')}function edit(item:Student){if(dirty&&!confirm('Tenés cambios sin guardar. ¿Querés descartarlos?'))return;setDraft({...item});setDirty(false);setMessage('');document.getElementById('student-form')?.scrollIntoView({behavior:'smooth'})}
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(false);setMessage('');try{const payload={...draft,schedule_ids:[...selected]};const r=await fetch('/api/admin/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json() as {error?:string;id:string};if(!r.ok)throw Error(data.error);setDraft(d=>({...d,id:data.id}));setDirty(false);setMessage('Alumna guardada.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos guardar la alumna.')}finally{setBusy(false)}}
async function remove(item:Student){if(!confirm(`¿Eliminar la ficha de ${item.name}?`))return;setBusy(true);setError(false);try{const r=await fetch('/api/admin/students?id='+encodeURIComponent(item.id),{method:'DELETE'});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);if(draft.id===item.id)reset();setMessage('Alumna eliminada.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos eliminar la alumna.')}finally{setBusy(false)}}
return <section className="admin-section"><div className="admin-section-head"><div><p className="eyebrow">MI TALLER</p><h2>Alumnas</h2><p>Creá fichas, guardá contactos y asigná uno o varios horarios fijos.</p></div><button className="button" onClick={reset} disabled={busy}>+ Nueva alumna</button></div><div className="feedback-slot" aria-live="polite">{message&&<p className={'feedback'+(error?' error':'')} role={error?'alert':'status'}>{message}</p>}</div>
<form id="student-form" className="admin-form team-form" onSubmit={submit}><div className="wide editor-heading"><div><p className="eyebrow">{draft.id?'EDITANDO':'CREANDO'}</p><h3>{draft.id?draft.name:'Nueva alumna'}</h3></div>{draft.id&&<button className="text-link" type="button" onClick={reset}>Cancelar edición</button>}</div><label>Nombre<input required maxLength={120} value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Estado<select value={draft.status} onChange={e=>update('status',e.target.value as StudentStatus)}>{Object.entries(studentStatusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Contacto principal<input maxLength={80} placeholder="WhatsApp o teléfono" value={draft.contact} onChange={e=>update('contact',e.target.value)}/></label><label>Mail<input type="email" maxLength={180} value={draft.email} onChange={e=>update('email',e.target.value)}/></label><label>Instagram<input maxLength={80} value={draft.instagram} onChange={e=>update('instagram',e.target.value)}/></label><label>Grupo familiar<input maxLength={120} placeholder="Ej.: mamá e hija / familia Pérez" value={draft.family_group} onChange={e=>update('family_group',e.target.value)}/></label><fieldset className="wide admin-checks"><legend>Horarios fijos</legend>{schedules.length?schedules.map(s=><label key={s.id} className="checkbox"><input type="checkbox" checked={selected.has(s.id)} onChange={()=>toggle(s.id)}/>{label(s)}</label>):<p>No hay horarios cargados todavía.</p>}</fieldset><label className="wide">Notas<textarea rows={4} maxLength={1200} value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label><div className="wide form-actions save-actions"><button className="button" type="submit" disabled={busy||!dirty}>{busy?'Guardando…':'Guardar alumna'}</button>{dirty&&<span className="note unsaved">Cambios sin guardar</span>}</div></form>
<h3 className="admin-list-title">Alumnas cargadas</h3>{loading?<div className="admin-loading" role="status"><span/>Actualizando alumnas…</div>:!items.length?<p>Todavía no cargaste alumnas.</p>:<div className="admin-schedule-list">{items.map(item=><article key={item.id}><div><strong>{item.name}</strong><p>{studentStatusLabels[item.status]} · {(item.schedule_ids?item.schedule_ids.split(',').length:0)} horario(s){item.family_group?' · '+item.family_group:''}</p></div><div><button className="button small secondary" onClick={()=>edit(item)} disabled={busy}>Editar</button><button className="text-link danger" onClick={()=>void remove(item)} disabled={busy}>Eliminar</button></div></article>)}</div>}</section>}
