'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {teamRoleLabels,type TeamMember,type TeamRole} from '../shared';

const blank:TeamMember={id:'',email:'',name:'',role:'team',active:1,created_at:'',updated_at:''};

export default function TeamEditor(){
  const[items,setItems]=useState<TeamMember[]>([]),[draft,setDraft]=useState<TeamMember>({...blank}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
  async function load(){setLoading(true);try{const r=await fetch('/api/admin/team');const data=await r.json() as {error?:string;members:TeamMember[]};if(!r.ok)throw Error(data.error);setItems(data.members)}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos cargar los accesos.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  function update<K extends keyof TeamMember>(key:K,value:TeamMember[K]){setDraft(d=>({...d,[key]:value}));setDirty(true)}
  function reset(){setDraft({...blank});setDirty(false);setMessage('')}
  function edit(item:TeamMember){if(dirty&&!confirm('Tenés cambios sin guardar. ¿Querés descartarlos?'))return;setDraft({...item});setDirty(false);setMessage('');document.getElementById('team-form')?.scrollIntoView({behavior:'smooth'})}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError(false);setMessage('');try{const r=await fetch('/api/admin/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const data=await r.json() as {error?:string;id:string};if(!r.ok)throw Error(data.error);setDraft(d=>({...d,id:data.id}));setDirty(false);setMessage(draft.active?'Acceso guardado y activo.':'Acceso guardado como inactivo.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos guardar el acceso.')}finally{setBusy(false)}}
  async function remove(item:TeamMember){if(!confirm(`¿Eliminar el acceso de ${item.email}?`))return;setBusy(true);setError(false);try{const r=await fetch('/api/admin/team?id='+encodeURIComponent(item.id),{method:'DELETE'});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);if(draft.id===item.id)reset();setMessage('Acceso eliminado.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos eliminar el acceso.')}finally{setBusy(false)}}
  return <section className="admin-section"><div className="admin-section-head"><div><p className="eyebrow">MI TALLER</p><h2>Equipo y accesos</h2><p>Habilitá mails del equipo y definí qué puede ver cada persona en el panel interno.</p></div><button className="button" onClick={reset} disabled={busy}>+ Nuevo acceso</button></div><div className="feedback-slot" aria-live="polite">{message&&<p className={'feedback'+(error?' error':'')} role={error?'alert':'status'}>{message}</p>}</div>
  <form id="team-form" className="admin-form team-form" onSubmit={submit}><div className="wide editor-heading"><div><p className="eyebrow">{draft.id?'EDITANDO':'CREANDO'}</p><h3>{draft.id?draft.email:'Nuevo acceso'}</h3></div>{draft.id&&<button className="text-link" type="button" onClick={reset}>Cancelar edición</button>}</div><label>Mail<input type="email" required maxLength={180} value={draft.email} onChange={e=>update('email',e.target.value)}/></label><label>Nombre visible<input maxLength={100} placeholder="Ej.: Agus, Juli, profe invitada" value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Rol<select value={draft.role} onChange={e=>update('role',e.target.value as TeamRole)}>{Object.entries(teamRoleLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={draft.active===1} onChange={e=>update('active',e.target.checked?1:0)}/>Acceso activo</label><div className="wide form-actions save-actions"><button className="button" type="submit" disabled={busy||!dirty}>{busy?'Guardando…':'Guardar acceso'}</button>{dirty&&<span className="note unsaved">Cambios sin guardar</span>}</div></form>
  <h3 className="admin-list-title">Accesos cargados</h3>{loading?<div className="admin-loading" role="status"><span/>Actualizando accesos…</div>:!items.length?<p>Todavía no cargaste accesos para el equipo.</p>:<div className="admin-schedule-list team-list">{items.map(item=><article key={item.id}><div><strong>{item.name||item.email}</strong><p>{item.email} · <span className={'team-role role-'+item.role}>{teamRoleLabels[item.role]}</span> · {item.active?'Activo':'Inactivo'}</p></div><div><button className="button small secondary" onClick={()=>edit(item)} disabled={busy}>Editar</button><button className="text-link danger" onClick={()=>void remove(item)} disabled={busy}>Eliminar</button></div></article>)}</div>}</section>
}
