import Catalog from './Catalog';
import { wa } from './shared';
const classes=wa('¡Hola Mud! Quisiera conocer los horarios y cómo inscribirme a las clases de cerámica.');
export default function Home(){return <>
<a className="skip" href="#contenido">Ir al contenido</a>
<div className="announcement">Un espacio para aprender, explorar y crear con las manos.</div>
<header className="header wrap"><a className="logo" href="#inicio">Mud<span>ESPACIO</span></a><nav aria-label="Navegación principal"><a href="#espacio">El espacio</a><a href="#clases">Clases</a><a href="#merch">Merch</a></nav><a className="button small" href={classes} target="_blank" rel="noreferrer">Escribinos ↗</a></header>
<main id="contenido"><section className="hero wrap" id="inicio"><div><p className="eyebrow">TALLER DE CERÁMICA · WILDE, BUENOS AIRES</p><h1>Un ratito<br/>para vos.<br/><em>Las manos<br/>en el barro.</em></h1><p className="intro">Aprender, explorar y darle forma a tus ideas.<br/>Te esperamos en Mud para crear y compartir.</p><a className="button" href={classes} target="_blank" rel="noreferrer">Quiero sumarme a las clases ↗</a><p className="note">Hablemos por WhatsApp y encontrá tu lugar.</p></div><div className="art" aria-hidden="true"><div className="art-paper"><span className="art-kicker">MENOS APURO,</span><span className="art-title">más<br/><i>barro.</i></span><span className="flower">✿</span><div className="pot"><div className="pot-rim"/><span>mud</span></div><span className="art-footer">CREAR TAMBIÉN ES ENCONTRARSE</span></div><span className="sticker">Hecho<br/>con las<br/><strong>manos ♥</strong></span><span className="spark">✳</span></div></section>
<div className="ribbon" aria-hidden="true"><span>HACER CON LAS MANOS</span>✳<span>DARLE FORMA A UNA IDEA</span>✳<span>COMPARTIR EL PROCESO</span>✳</div>
<section className="about wrap section" id="espacio"><div><p className="eyebrow">HOLA, SOMOS MUD</p><h2>Un espacio para<br/>hacer lugar a<br/><em>lo creativo.</em></h2></div><div className="about-copy"><span className="little-flower" aria-hidden="true">✿</span><p>En Mud nos encontramos alrededor de la cerámica: las manos en movimiento, las ideas tomando forma y el placer de crear algo propio.</p><p>Somos un taller en Wilde, Buenos Aires. Un espacio para aprender, explorar materiales y compartir el proceso con otras personas.</p><a className="text-link" href="https://www.instagram.com/mudespacio/" target="_blank" rel="noreferrer">Conocé el día a día en Instagram ↗</a></div></section>
<section className="classes" id="clases"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">TU PRÓXIMO MOMENTO CREATIVO</p><h2>Nos vemos<br/><em>en el taller.</em></h2></div><p>Si tenés ganas de empezar o seguir explorando la cerámica, escribinos. Te contamos cómo son las clases y qué horarios hay disponibles.</p></div><div className="steps">{[['01','Charlamos','Contanos qué te gustaría aprender y consultanos tus dudas.'],['02','Buscamos tu horario','Te compartimos los días, horarios y lugares disponibles.'],['03','Coordinamos tu inscripción','Te contamos los detalles para sumarte al espacio.']].map(([n,t,d])=><article key={n}><span>{n} /</span><h3>{t}</h3><p>{d}</p></article>)}</div><a className="button cream" href={classes} target="_blank" rel="noreferrer">Consultar clases e inscripción ↗</a></div></section>
<section className="wrap section" id="merch"><div className="section-heading"><div><p className="eyebrow">MERCH PROPIA DEL ESPACIO</p><h2>Un pedacito<br/><em>de Mud con vos.</em></h2></div><p>Para darte un gusto o hacer un regalo con nuestra personalidad. Elegí lo que te guste y escribinos para coordinar tu encargo.</p></div><Catalog/></section>
<section className="payment wrap"><span className="payment-icon" aria-hidden="true">✳</span><div><h3>Así podés pagar</h3><p>Coordinamos los detalles por WhatsApp.</p></div><div className="payment-options"><span>Transferencia bancaria</span><span>Efectivo</span></div></section>
<section className="contact wrap section"><p className="eyebrow">EL PRIMER PASO ES UN HOLA</p><h2>¿Hacemos<br/><em>algo lindo?</em> <span aria-hidden="true">✿</span></h2><a className="button" href={wa('¡Hola Mud! Quisiera hacerles una consulta.')} target="_blank" rel="noreferrer">Hablemos por WhatsApp ↗</a><p>Wilde, Buenos Aires, Argentina<br/><a href="tel:+5491139148205">11 3914-8205</a></p></section></main>
<a className="mobile-contact" href={classes} target="_blank" rel="noreferrer" aria-label="Consultar clases por WhatsApp"><span aria-hidden="true">✦</span> Consultar clases</a>
<footer className="wrap footer"><a className="logo" href="#inicio">Mud<span>ESPACIO</span></a><p>Aprender. Explorar. Crear.</p><a href="https://www.instagram.com/mudespacio/" target="_blank" rel="noreferrer">@mudespacio ↗</a><a href="/admin">Administrar</a><span>© {new Date().getFullYear()} Mud Espacio</span></footer></>}
