import {env} from 'cloudflare:workers';
import {getChatGPTUser} from './chatgpt-auth';
import type {AttendanceRecord,ClassSession,ClosureDay,PortalAbsenceRequest,Product,RecoveryBooking,RecoveryCredit,Schedule,StaffMember,StaffPayment,Student,StudentPayment,TeamMember,TeamRole,WaitlistEntry,WorkLog,WorkshopExpense} from './shared';
export function bindings(){return env as unknown as {DB:D1Database;PRODUCT_IMAGES:R2Bucket;ADMIN_EMAIL?:string}}
export async function isAdmin(){const user=await getChatGPTUser();const email=bindings().ADMIN_EMAIL;return !!(user&&email&&user.email.toLowerCase()===email.trim().toLowerCase())}
export async function guard(request:Request){if(!await isAdmin())return Response.json({error:'Necesitás ingresar con la cuenta administradora.'},{status:403});if(request.method!=='GET'&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origen no permitido.'},{status:403});return null}
export async function database(){const db=bindings().DB;if(!db)throw Error('Database unavailable');await db.prepare("CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', price INTEGER, variants TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'order', published INTEGER NOT NULL DEFAULT 0, image TEXT NOT NULL DEFAULT '', sort INTEGER NOT NULL DEFAULT 0)").run();return db}
export async function listProducts(admin=false){const db=await database();const {results}=await db.prepare(admin?'SELECT * FROM products ORDER BY sort, name':'SELECT * FROM products WHERE published=1 ORDER BY sort, name').all<Product>();return results}
const scheduleSelect=`SELECT s.*, st.name AS teacher_name, (SELECT COUNT(*) FROM student_schedules ss JOIN students stu ON stu.id=ss.student_id WHERE ss.schedule_id=s.id AND stu.status!='inactive') AS student_count FROM schedules s LEFT JOIN staff_members st ON st.id=s.teacher_id`;
export async function listSchedules(admin=false){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare((admin?scheduleSelect:scheduleSelect+" WHERE s.published=1")+' ORDER BY s.day, s.sort, s.start').all<Schedule>();return results}
export async function listTeamMembers(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare('SELECT * FROM team_members ORDER BY active DESC, role, email').all<TeamMember>();return results}
export async function listStudents(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare("SELECT st.*, COALESCE((SELECT group_concat(schedule_id) FROM student_schedules WHERE student_id=st.id),'') AS schedule_ids FROM students st ORDER BY CASE st.status WHEN 'active' THEN 0 WHEN 'interested' THEN 1 WHEN 'paused' THEN 2 ELSE 3 END, st.name").all<Student>();return results}
export async function listStaffMembers(kind?:string){const db=bindings().DB;if(!db)throw Error('Database unavailable');const sql=kind?'SELECT * FROM staff_members WHERE kind=? ORDER BY status, name':'SELECT * FROM staff_members ORDER BY CASE kind WHEN "teacher" THEN 0 ELSE 1 END, status, name';const stmt=db.prepare(sql);const {results}=kind?await stmt.bind(kind).all<StaffMember>():await stmt.all<StaffMember>();return results}
const scheduleLabel="(CASE s.day WHEN 1 THEN 'Lunes' WHEN 2 THEN 'Martes' WHEN 3 THEN 'Miércoles' WHEN 4 THEN 'Jueves' WHEN 5 THEN 'Viernes' WHEN 6 THEN 'Sábado' ELSE 'Domingo' END || ' ' || s.start || '-' || s.end)";
export async function listClassSessions(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare(`SELECT cs.*, ${scheduleLabel} AS schedule_label, st.name AS teacher_name FROM class_sessions cs JOIN schedules s ON s.id=cs.schedule_id LEFT JOIN staff_members st ON st.id=s.teacher_id ORDER BY cs.date DESC, s.day, s.start`).all<ClassSession>();return results}
export async function listAttendanceRecords(sessionId?:string){const db=bindings().DB;if(!db)throw Error('Database unavailable');const sql=`SELECT ar.*, stu.name AS student_name FROM attendance_records ar JOIN students stu ON stu.id=ar.student_id ${sessionId?'WHERE ar.session_id=?':''} ORDER BY ar.created_at DESC`;const stmt=db.prepare(sql);const {results}=sessionId?await stmt.bind(sessionId).all<AttendanceRecord>():await stmt.all<AttendanceRecord>();return results}
export async function listRecoveryCredits(status?:string){const db=bindings().DB;if(!db)throw Error('Database unavailable');const sql=`SELECT rc.*, stu.name AS student_name FROM recovery_credits rc JOIN students stu ON stu.id=rc.student_id ${status?'WHERE rc.status=?':''} ORDER BY rc.created_at DESC`;const stmt=db.prepare(sql);const {results}=status?await stmt.bind(status).all<RecoveryCredit>():await stmt.all<RecoveryCredit>();return results}
export async function listRecoveryBookings(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare(`SELECT rb.*, stu.name AS student_name, cs.date AS class_date, ${scheduleLabel} AS schedule_label FROM recovery_bookings rb JOIN students stu ON stu.id=rb.student_id JOIN class_sessions cs ON cs.id=rb.session_id JOIN schedules s ON s.id=cs.schedule_id ORDER BY cs.date DESC, rb.created_at DESC`).all<RecoveryBooking>();return results}
export async function listClosureDays(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare('SELECT * FROM closure_days ORDER BY date DESC').all<ClosureDay>();return results}
export async function listWaitlistEntries(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare(`SELECT we.*, stu.name AS student_name, ${scheduleLabel} AS schedule_label FROM waitlist_entries we JOIN students stu ON stu.id=we.student_id JOIN schedules s ON s.id=we.schedule_id ORDER BY CASE we.status WHEN 'interested' THEN 0 WHEN 'waiting' THEN 1 WHEN 'contacted' THEN 2 WHEN 'converted' THEN 3 ELSE 4 END, we.updated_at DESC`).all<WaitlistEntry>();return results}
export async function listStudentPayments(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare(`SELECT sp.*, stu.name AS student_name, ${scheduleLabel} AS schedule_label FROM student_payments sp JOIN students stu ON stu.id=sp.student_id LEFT JOIN schedules s ON s.id=sp.schedule_id ORDER BY sp.period DESC, sp.updated_at DESC`).all<StudentPayment>();return results}
export async function listWorkshopExpenses(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare('SELECT * FROM workshop_expenses ORDER BY period DESC, expense_date DESC').all<WorkshopExpense>();return results}
export async function listWorkLogs(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare('SELECT wl.*, st.name AS staff_name FROM work_logs wl JOIN staff_members st ON st.id=wl.staff_id ORDER BY wl.work_date DESC, wl.updated_at DESC').all<WorkLog>();return results}
export async function listWorkLogsForEmail(email:string){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare('SELECT wl.*, st.name AS staff_name FROM work_logs wl JOIN staff_members st ON st.id=wl.staff_id WHERE lower(st.email)=? ORDER BY wl.work_date DESC, wl.updated_at DESC').bind(email.trim().toLowerCase()).all<WorkLog>();return results}
export async function staffMemberForEmail(email:string){const db=bindings().DB;if(!db)throw Error('Database unavailable');return db.prepare('SELECT * FROM staff_members WHERE lower(email)=? LIMIT 1').bind(email.trim().toLowerCase()).first<StaffMember>()}
export async function listStaffPayments(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare('SELECT sp.*, st.name AS staff_name FROM staff_payments sp JOIN staff_members st ON st.id=sp.staff_id ORDER BY sp.period DESC, sp.updated_at DESC').all<StaffPayment>();return results}
export async function listPortalAbsenceRequests(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare("SELECT * FROM portal_absence_requests ORDER BY CASE status WHEN 'pending' THEN 0 WHEN 'reviewed' THEN 1 WHEN 'resolved' THEN 2 ELSE 3 END, created_at DESC").all<PortalAbsenceRequest>();return results}
export async function getWorkshopAccess(email:string){const normalized=email.trim().toLowerCase();const owner=(bindings().ADMIN_EMAIL||'').trim().toLowerCase();if(owner&&normalized===owner)return {email:normalized,name:'Agustina',role:'admin' as TeamRole,active:1,source:'owner' as const};const db=bindings().DB;if(!db)throw Error('Database unavailable');const member=await db.prepare('SELECT * FROM team_members WHERE email=? AND active=1 LIMIT 1').bind(normalized).first<TeamMember>();return member?{email:member.email,name:member.name||member.email,role:member.role,active:member.active,source:'team' as const}:null}
export async function canManageWorkshop(){const user=await getChatGPTUser();if(!user)return false;const access=await getWorkshopAccess(user.email);return access?.role==='admin'}

