import {env} from 'cloudflare:workers';
import {getChatGPTUser} from './chatgpt-auth';
import type {Product,Schedule,TeamMember,TeamRole} from './shared';
export function bindings(){return env as unknown as {DB:D1Database;PRODUCT_IMAGES:R2Bucket;ADMIN_EMAIL?:string}}
export async function isAdmin(){const user=await getChatGPTUser();const email=bindings().ADMIN_EMAIL;return !!(user&&email&&user.email.toLowerCase()===email.trim().toLowerCase())}
export async function guard(request:Request){if(!await isAdmin())return Response.json({error:'Necesitás ingresar con la cuenta administradora.'},{status:403});if(request.method!=='GET'&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origen no permitido.'},{status:403});return null}
export async function database(){const db=bindings().DB;if(!db)throw Error('Database unavailable');await db.prepare("CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', price INTEGER, variants TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'order', published INTEGER NOT NULL DEFAULT 0, image TEXT NOT NULL DEFAULT '', sort INTEGER NOT NULL DEFAULT 0)").run();return db}
export async function listProducts(admin=false){const db=await database();const {results}=await db.prepare(admin?'SELECT * FROM products ORDER BY sort, name':'SELECT * FROM products WHERE published=1 ORDER BY sort, name').all<Product>();return results}
export async function listSchedules(admin=false){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare(admin?'SELECT * FROM schedules ORDER BY day, sort, start':'SELECT * FROM schedules WHERE published=1 ORDER BY day, sort, start').all<Schedule>();return results}
export async function listTeamMembers(){const db=bindings().DB;if(!db)throw Error('Database unavailable');const {results}=await db.prepare('SELECT * FROM team_members ORDER BY active DESC, role, email').all<TeamMember>();return results}
export async function getWorkshopAccess(email:string){const normalized=email.trim().toLowerCase();const owner=(bindings().ADMIN_EMAIL||'').trim().toLowerCase();if(owner&&normalized===owner)return {email:normalized,name:'Agustina',role:'admin' as TeamRole,active:1,source:'owner' as const};const db=bindings().DB;if(!db)throw Error('Database unavailable');const member=await db.prepare('SELECT * FROM team_members WHERE email=? AND active=1 LIMIT 1').bind(normalized).first<TeamMember>();return member?{email:member.email,name:member.name||member.email,role:member.role,active:member.active,source:'team' as const}:null}
export async function canManageWorkshop(){const user=await getChatGPTUser();if(!user)return false;const access=await getWorkshopAccess(user.email);return access?.role==='admin'}

