'use client';
import {useEffect,useMemo,useState} from 'react';
import {attendanceStatusLabels,type AttendanceStatus} from '../shared';

type SheetStudent={id:string;name:string;attendance:null|{id:string;status:AttendanceStatus;credit_id:string|null;notes:string}};
type SheetClass={id:string;date:string;start:string;end:string;schedule_label:string;teacher_name?:string;students:SheetStudent[]};
type SheetData={period:string;canWrite:boolean;classes:SheetClass[]};
const month=()=>new Date().toISOString().slice(0,7);
const statuses:AttendanceStatus[]=['present','absent','notice'];

export default function AttendanceSheet({readOnly=false}:{readOnly?:boolean}){
  const[period,setPeriod]=useState(month()),[data,setData]=useState<SheetData|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
  async function load(p=period){setBusy(true);setError(false);try{const r=await fetch('/api/mitaller/attendance?period='+encodeURIComponent(p));const d=await r.json() as SheetData&{error?:string};if(!r.ok)throw Error(d.error);setData(d)}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos cargar la planilla.')}finally{setBusy(false)}}useEffect(()=>{void load()},[]);
  const canWrite=!!data?.canWrite&&!readOnly;
  async function save(cls:SheetClass,student:SheetStudent,status:AttendanceStatus,grant_credit:boolean,notes=''){if(!canWrite)return;setBusy(true);setError(false);try{const r=await fetch('/api/mitaller/attendance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:cls.id,student_id:student.id,status,grant_credit,notes})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setMessage('Asistencia actualizada.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos guardar la asistencia.')}finally{setBusy(false)}}
  const totals=useMemo(()=>{const all=data?.classes.flatMap(c=>c.students.map(s=>s.attendance?.status||'pending'))||[];return {present:all.filter(s=>s==='present').length,absent:all.filter(s=>s==='absent'||s==='notice').length,pending:all.filter(s=>s==='pending').length}},[data]);
  function exportCsv(){if(!data)return;const rows=[['Fecha','Clase','Profe','Alumna','Estado','Recupero','Notas'],...data.classes.flatMap(c=>c.students.map(s=>[c.date,c.schedule_label,c.teacher_name||'',s.name,s.attendance?attendanceStatusLabels[s.attendance.status]:'Sin cargar',s.attendance?.credit_id?'Sí':'No',s.attendance?.notes||'']))];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`mud-asistencias-${period}.csv`;a.click();URL.revokeObjectURL(url)}
  return <section className="workshop-panel attendance-sheet-panel"><div><p className="eyebrow">ASISTENCIAS</p><h2>Planilla mensual</h2><p>Clases precargadas desde la grilla. Marcá presentes, ausentes y otorgá recupero manual cuando corresponda.</p><div className="attendance-sheet-tools"><label>Mes<input type="month" value={period} onChange={e=>{setPeriod(e.target.value);void load(e.target.value)}}/></label><button className="button secondary" type="button" onClick={exportCsv} disabled={!data}>Exportar CSV</button></div>{message&&<p className={'feedback'+(error?' error':'')}>{message}</p>}<div className="attendance-sheet-summary"><span>{totals.present} presentes</span><span>{totals.absent} ausencias</span><span>{totals.pending} sin cargar</span></div>{readOnly&&<p className="note">Tu rol es de lectura: podés revisar y exportar, pero no editar.</p>}</div><div className="attendance-sheet-scroll">{busy&&!data?<div className="admin-loading"><span/>Cargando planilla…</div>:data?.classes.length?<div className="attendance-sheet-list">{data.classes.map(cls=><article key={cls.id} className="attendance-class"><header><div><strong>{cls.date} · {cls.schedule_label}</strong><small>{cls.teacher_name||'Sin profe asignada'} · {cls.students.length} alumna(s)</small></div></header><div className="attendance-rows">{cls.students.map(st=>{const current=st.attendance?.status||'';return <div key={st.id} className="attendance-row"><strong>{st.name}</strong><select disabled={!canWrite||busy} value={current} onChange={e=>void save(cls,st,e.target.value as AttendanceStatus,!!st.attendance?.credit_id,st.attendance?.notes||'')}><option value="">Sin cargar</option>{statuses.map(s=><option key={s} value={s}>{attendanceStatusLabels[s]}</option>)}</select><label className="attendance-credit"><input type="checkbox" disabled={!canWrite||busy||current==='present'||current===''} checked={!!st.attendance?.credit_id} onChange={e=>void save(cls,st,(current||'absent') as AttendanceStatus,e.target.checked,st.attendance?.notes||'')}/>Dar recupero</label><input disabled={!canWrite||busy} placeholder="Nota" defaultValue={st.attendance?.notes||''} onBlur={e=>current&&void save(cls,st,current as AttendanceStatus,!!st.attendance?.credit_id,e.target.value)}/></div>})}</div></article>)}</div>:<p className="workshop-empty">No hay clases para ese mes. La planilla genera clases automáticamente desde la grilla visible.</p>}</div></section>
}
