import {requireChatGPTUser} from '../chatgpt-auth';
import {getWorkshopAccess,listRecoveryCredits,listSchedules,listStaffMembers,listStaffPayments,listStudentPayments,listStudents,listTeamMembers,listWaitlistEntries,listWorkshopExpenses} from '../server';
import {creditStatusLabels,dayLabels,rolePermissionNotes,scheduleStatusLabels,staffKindLabels,teamRoleLabels,waitlistStatusLabels,type ScheduleStatus} from '../shared';
import AssistantHours from './AssistantHours';

export const dynamic='force-dynamic';
const statusOrder:ScheduleStatus[]=['open','last','forming','full'];
const statusTone:Record<ScheduleStatus,string>={open:'ok',last:'warn',forming:'soft',full:'muted'};

export default async function MiTaller(){
  const user=await requireChatGPTUser('/mitaller');
  const access=await getWorkshopAccess(user.email);
  if(!access)return <main className="workshop-shell access-denied"><a className="text-link" href="/">Volver al sitio</a><section><p className="eyebrow">MI TALLER</p><h1>Acceso reservado.</h1><p>Este panel está en beta y solo pueden entrar los mails habilitados por Mud Espacio.</p><a className="button" href="/signout-with-chatgpt?return_to=%2Fmitaller">Cambiar de cuenta</a></section></main>;
  const schedules=await listSchedules(true),members=access.role==='admin'?await listTeamMembers():[],students=await listStudents(),staff=await listStaffMembers(),credits=await listRecoveryCredits('available'),waitlist=await listWaitlistEntries(),studentPayments=await listStudentPayments(),expenses=await listWorkshopExpenses(),staffPayments=await listStaffPayments();
  const todayDay=new Date(new Date().toLocaleString('en-US',{timeZone:'America/Argentina/Buenos_Aires'})).getDay();
  const today=schedules.filter(s=>s.day===todayDay),published=schedules.filter(s=>s.published===1).length,available=schedules.filter(s=>s.status==='open'||s.status==='last').length,forming=schedules.filter(s=>s.status==='forming').length;
  const statusCounts=Object.fromEntries(statusOrder.map(status=>[status,schedules.filter(s=>s.status===status).length])) as Record<ScheduleStatus,number>,period=new Date().toISOString().slice(0,7),money=(n:number)=>'$'+(n/100).toLocaleString('es-AR');
  const income=studentPayments.filter(p=>p.period===period).reduce((a,p)=>a+p.paid_amount,0),spent=expenses.filter(e=>e.period===period).reduce((a,e)=>a+e.amount,0)+staffPayments.filter(p=>p.period===period&&p.status==='paid').reduce((a,p)=>a+p.amount,0);
  const groups=Object.entries(Object.groupBy(schedules,s=>String(s.day))).sort(([a],[b])=>Number(a)-Number(b));
  return <main className="workshop-shell"><header className="workshop-header"><div><p className="eyebrow">MI TALLER</p><h1>Dashboard.</h1><p>Hola {access.name}. Entraste como {teamRoleLabels[access.role]}.</p></div><nav><a className="text-link" href="/">Sitio</a>{access.role==='admin'&&<a className="text-link" href="/admin#admin-alumnas">Gestionar</a>}<a className="text-link" href="/signout-with-chatgpt?return_to=%2F">Salir</a></nav></header>
  <section className="workshop-metrics" aria-label="Resumen del taller"><article><span>Alumnas registradas</span><strong>{students.length}</strong><small>{students.filter(s=>s.status==='active').length} activas</small></article><article><span>Recuperaciones</span><strong>{credits.length}</strong><small>Créditos disponibles</small></article><article><span>Lista de espera</span><strong>{waitlist.length}</strong><small>Interesadas y pendientes</small></article></section>
  <section className="workshop-layout">
    <div className="workshop-main">
      {(access.role==='assistant'||access.role==='admin')&&<AssistantHours/>}
      <section className="workshop-panel today-panel"><div><p className="eyebrow">HOY</p><h2>{dayLabels[todayDay]}</h2><p>{today.length?'Estos son los grupos cargados para hoy.':'No hay grupos cargados para hoy.'}</p></div><div className="workshop-schedule">{today.length?today.map(s=><article key={s.id}><div><strong>{s.start} a {s.end}</strong><p>{s.note||'Sin nota interna todavía'}</p></div><span className={'tone-'+statusTone[s.status]}>{scheduleStatusLabels[s.status]}</span></article>):<p className="workshop-empty">Podés usar este espacio para ver clases del día, asistencia y pendientes cuando sumemos alumnos.</p>}</div></section>
      <section className="workshop-panel"><div><p className="eyebrow">SEMANA</p><h2>Grilla operativa</h2><p>Vista interna de horarios con profe asignada y cantidad de alumnas vinculadas.</p></div><div className="workshop-days">{groups.map(([day,slots])=><article key={day}><h3>{dayLabels[Number(day)]}</h3>{slots!.map(s=><div className="workshop-row" key={s.id}><div><strong>{s.start} a {s.end}</strong><p>{s.teacher_name||'Sin profe'} · {s.student_count||0} alumna(s){s.note?' · '+s.note:''}</p></div><span className={'tone-'+statusTone[s.status]}>{scheduleStatusLabels[s.status]}</span></div>)}</article>)}</div></section>
    </div>
    <aside className="workshop-side">
      <section><p className="eyebrow">ESTADOS</p><h2>Cupos</h2><div className="workshop-status-list">{statusOrder.map(status=><div key={status}><span className={'dot tone-'+statusTone[status]}/><strong>{scheduleStatusLabels[status]}</strong><em>{statusCounts[status]}</em></div>)}</div></section>
      <section><p className="eyebrow">ACCIONES</p><h2>Atajos</h2><div className="workshop-actions">{access.role==='admin'&&<><a href="/admin#admin-alumnas">Alumnas</a><a href="/admin#admin-staff">Profes y equipo</a><a href="/admin#admin-horarios">Horarios</a><a href="/admin#admin-asistencia">Asistencia</a><a href="/admin#admin-productos">Productos</a></>}<span>Pagos: próxima fase</span></div></section>
      <section><p className="eyebrow">RECUPERACIONES</p><h2>Créditos</h2><div className="workshop-team">{credits.length?credits.slice(0,5).map(c=><article key={c.id}><strong>{c.student_name}</strong><span>{creditStatusLabels[c.status]} · vence {c.expires_at||'sin fecha'}</span></article>):<article><strong>Sin pendientes</strong><span>No hay créditos disponibles.</span></article>}</div></section>
      <section><p className="eyebrow">INTERESADAS</p><h2>Espera</h2><div className="workshop-team">{waitlist.length?waitlist.slice(0,5).map(w=><article key={w.id}><strong>{w.student_name}</strong><span>{waitlistStatusLabels[w.status]} · {w.schedule_label}</span></article>):<article><strong>Sin lista</strong><span>No hay interesadas cargadas.</span></article>}</div></section>
      <section><p className="eyebrow">ECONOMÍA</p><h2>Mes</h2><div className="workshop-status-list"><div><span className="dot tone-ok"/><strong>Cobrado</strong><em>{money(income)}</em></div><div><span className="dot tone-warn"/><strong>Gastos</strong><em>{money(spent)}</em></div><div><span className="dot tone-soft"/><strong>Balance</strong><em>{money(income-spent)}</em></div></div></section>
      {access.role==='admin'&&<section><p className="eyebrow">EQUIPO</p><h2>Operativo</h2><div className="workshop-team">{staff.length?staff.slice(0,6).map(m=><article key={m.id}><strong>{m.name}</strong><span>{staffKindLabels[m.kind]} · {m.status==='active'?'Activa':m.status==='paused'?'Pausada':'Inactiva'}</span></article>):<article><strong>Sin fichas</strong><span>Cargalas desde Admin.</span></article>}</div></section>}
      {access.role==='admin'&&<section><p className="eyebrow">EQUIPO</p><h2>Accesos</h2><div className="workshop-team"><article><strong>Agustina</strong><span>Admin</span></article>{members.map(m=><article key={m.id}><strong>{m.name||m.email}</strong><span>{teamRoleLabels[m.role]} · {m.active?'Activo':'Inactivo'}</span></article>)}</div></section>}
      {access.role==='admin'&&<section><p className="eyebrow">PERMISOS</p><h2>Roles</h2><div className="workshop-team">{Object.entries(rolePermissionNotes).map(([role,notes])=><article key={role}><strong>{teamRoleLabels[role as keyof typeof teamRoleLabels]}</strong><span>{notes.join(' · ')}</span></article>)}</div></section>}
    </aside>
  </section>
  <section className="workshop-next"><p className="eyebrow">FASE 1</p><h2>Base operativa lista para completar</h2><ul><li>Fichas de alumnas con varios horarios posibles.</li><li>Fichas de profes, asistentes, CM, limpieza y administración.</li><li>Horarios conectados con profe asignada y alumnas vinculadas.</li></ul></section></main>
}
