'use client';
import {useState,type FormEvent} from 'react';
import type {RecoveryCredit} from '../shared';
const today=()=>new Date().toISOString().slice(0,10);
const month=()=>new Date().toISOString().slice(0,7);
type RecoveryClass={id:string;date:string;start:string;end:string;teacher_name?:string;capacity:number;fixed_count:number;recovery_count:number;available:number};
type PortalData={student:{id:string;name:string};credits:RecoveryCredit[];classes:RecoveryClass[]};
export default function StudentPortal(){const[form,setForm]=useState({student_name:'',contact:'',class_date:today(),schedule_hint:'',message:''}),[lookup,setLookup]=useState({contact:'',period:month()}),[data,setData]=useState<PortalData|null>(null),[booking,setBooking]=useState({credit_id:'',session_id:'',notes:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
async function submitAbsence(e:FormEvent){e.preventDefault();setBusy(true);setError(false);setMessage('');try{const r=await fetch('/api/portal/absence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setMessage('Aviso enviado. El equipo de Mud lo revisa y confirma si corresponde recuperación.');setForm({student_name:'',contact:'',class_date:today(),schedule_hint:'',message:''})}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos enviar el aviso.')}finally{setBusy(false)}}
async function loadRecoveries(e?:FormEvent){e?.preventDefault();setBusy(true);setError(false);setMessage('');try{const params=new URLSearchParams({contact:lookup.contact,period:lookup.period});const r=await fetch('/api/portal/recoveries?'+params.toString());const d=await r.json() as PortalData&{error?:string};if(!r.ok)throw Error(d.error);setData(d);setBooking({credit_id:d.credits[0]?.id||'',session_id:d.classes.find(c=>c.available>0)?.id||'',notes:''});setMessage(`Encontramos los recuperos de ${d.student.name}.`)}catch(e){setData(null);setError(true);setMessage(e instanceof Error?e.message:'No pudimos consultar recuperos.')}finally{setBusy(false)}}
async function reserveRecovery(e:FormEvent){e.preventDefault();setBusy(true);setError(false);setMessage('');try{const r=await fetch('/api/portal/recoveries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...booking,contact:lookup.contact})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setMessage('Reserva enviada. Queda pendiente de confirmación del equipo de Mud.');await loadRecoveries()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos reservar ese recupero.')}finally{setBusy(false)}}
const availableClasses=data?.classes.filter(c=>c.available>0)||[];
return <main className="student-portal"><section><p className="eyebrow">MUD ESPACIO</p><h1>Portal alumnas.</h1><p>Avisá una ausencia o consultá tus recuperos disponibles. Para generar crédito, el aviso tiene que llegar con al menos 6 horas de anticipación.</p>{message&&<p className={'feedback'+(error?' error':'')}>{message}</p>}
<div className="portal-grid">
<form className="admin-form compact-form portal-card" onSubmit={submitAbsence}><div className="wide editor-heading"><div><p className="eyebrow">AUSENCIAS</p><h3>Avisar que no venís</h3></div></div><label>Nombre y apellido<input required value={form.student_name} onChange={e=>setForm({...form,student_name:e.target.value})}/></label><label>Contacto<input required placeholder="WhatsApp, mail o Instagram cargado" value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label><label>Fecha de la clase<input type="date" required value={form.class_date} onChange={e=>setForm({...form,class_date:e.target.value})}/></label><label>Horario o profe<input placeholder="Ej.: martes 11, viernes 17, profe..." value={form.schedule_hint} onChange={e=>setForm({...form,schedule_hint:e.target.value})}/></label><label className="wide">Mensaje opcional<textarea rows={4} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button className="button wide" disabled={busy}>{busy?'Enviando…':'Avisar ausencia'}</button></form>
<form className="admin-form compact-form portal-card" onSubmit={loadRecoveries}><div className="wide editor-heading"><div><p className="eyebrow">RECUPEROS</p><h3>Ver horarios disponibles</h3></div></div><label className="wide">Tu contacto<input required placeholder="El mismo WhatsApp, mail o Instagram de tu ficha" value={lookup.contact} onChange={e=>setLookup({...lookup,contact:e.target.value})}/></label><label>Mes<input type="month" required value={lookup.period} onChange={e=>setLookup({...lookup,period:e.target.value})}/></label><p className="wide note">Mostramos clases con cupo real: cupo máximo menos alumnas fijas y recuperos ya reservados.</p><button className="button wide" disabled={busy}>{busy?'Consultando…':'Consultar recuperos'}</button></form>
</div>
{data&&<section className="portal-results"><div><p className="eyebrow">TUS CRÉDITOS</p><h2>{data.student.name}</h2>{data.credits.length?<div className="portal-list">{data.credits.map(c=><article key={c.id}><strong>Crédito disponible</strong><p>Vence {c.expires_at||'sin fecha'}{c.notes?' · '+c.notes:''}</p></article>)}</div>:<p>No tenés créditos disponibles para reservar.</p>}</div><div><p className="eyebrow">CALENDARIO DE RECUPEROS</p><h2>Clases con cupo</h2>{data.classes.length?<div className="portal-list">{data.classes.map(c=><article key={c.id} className={c.available>0?'':'muted'}><strong>{c.date} · {c.start} a {c.end}</strong><p>{c.teacher_name||'Sin profe asignada'} · {c.available>0?`${c.available} cupo(s) para recuperar`:'Sin cupos disponibles'}</p></article>)}</div>:<p>Todavía no hay clases generadas para ese mes.</p>}</div>{data.credits.length>0&&availableClasses.length>0&&<form className="admin-form compact-form portal-card" onSubmit={reserveRecovery}><div className="wide editor-heading"><div><p className="eyebrow">RESERVA</p><h3>Elegir recupero</h3></div></div><label className="wide">Crédito<select required value={booking.credit_id} onChange={e=>setBooking({...booking,credit_id:e.target.value})}>{data.credits.map(c=><option key={c.id} value={c.id}>Vence {c.expires_at||'sin fecha'}{c.notes?' · '+c.notes:''}</option>)}</select></label><label className="wide">Clase<select required value={booking.session_id} onChange={e=>setBooking({...booking,session_id:e.target.value})}>{availableClasses.map(c=><option key={c.id} value={c.id}>{c.date} · {c.start}-{c.end} · {c.available} cupo(s)</option>)}</select></label><label className="wide">Nota opcional<input maxLength={500} value={booking.notes} onChange={e=>setBooking({...booking,notes:e.target.value})}/></label><button className="button wide" disabled={busy}>Reservar recupero</button></form>}</section>}
<p className="note">Las reservas quedan pendientes hasta que el equipo las confirme desde el panel.</p><a className="text-link" href="/">Volver al sitio</a></section></main>}
