'use client';
import {useEffect,useMemo,useState,type FormEvent} from 'react';
const month=()=>new Date().toISOString().slice(0,7);
type Student={id:string;name:string;email:string;contact:string;instagram:string;family_group:string;notes:string};
type MyClass={id:string;date:string;start:string;end:string;schedule_label:string;teacher_name?:string;attendance_status?:string;credit_id?:string|null};
type Credit={id:string;expires_at:string;notes:string;status:string};
type RecoveryClass={id:string;date:string;start:string;end:string;schedule_label:string;teacher_name?:string;available:number};
type Booking={id:string;class_date:string;schedule_label:string;status:string};
type PortalData={student:Student;myClasses:MyClass[];credits:Credit[];bookings:Booking[];recoveryClasses:RecoveryClass[]};
const auth=(token:string)=>({Authorization:'Bearer '+token,'Content-Type':'application/json'});
export default function StudentPortal(){const[token,setToken]=useState(''),[login,setLogin]=useState({email:'',password:''}),[period,setPeriod]=useState(month()),[data,setData]=useState<PortalData|null>(null),[profile,setProfile]=useState<Student|null>(null),[selected,setSelected]=useState<MyClass|RecoveryClass|null>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
useEffect(()=>{const saved=localStorage.getItem('mud_student_token')||'';if(saved){setToken(saved);void load(saved,period)}},[]);
async function load(t=token,p=period){if(!t)return;setBusy(true);setError(false);try{const r=await fetch('/api/portal/me?period='+encodeURIComponent(p),{headers:{Authorization:'Bearer '+t}});const d=await r.json() as PortalData&{error?:string};if(!r.ok)throw Error(d.error);setData(d);setProfile(d.student);setSelected(null);setNote('')}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos cargar tu portal.');if((e instanceof Error)&&e.message.includes('ingresar')){localStorage.removeItem('mud_student_token');setToken('')}}finally{setBusy(false)}}
async function submitLogin(e:FormEvent){e.preventDefault();setBusy(true);setError(false);setMessage('');try{const r=await fetch('/api/portal/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const d=await r.json() as {token:string;error?:string};if(!r.ok)throw Error(d.error);localStorage.setItem('mud_student_token',d.token);setToken(d.token);await load(d.token,period);setMessage('Entraste a tu portal.')}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos iniciar sesión.')}finally{setBusy(false)}}
async function saveProfile(e:FormEvent){e.preventDefault();if(!profile)return;setBusy(true);setError(false);try{const r=await fetch('/api/portal/me',{method:'PUT',headers:auth(token),body:JSON.stringify(profile)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setMessage('Ficha actualizada.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos guardar tu ficha.')}finally{setBusy(false)}}
async function absence(cls:MyClass){setBusy(true);setError(false);try{const r=await fetch('/api/portal/absence',{method:'POST',headers:auth(token),body:JSON.stringify({session_id:cls.id,message:note})});const d=await r.json() as {error?:string;credit_created?:boolean};if(!r.ok)throw Error(d.error);setMessage(d.credit_created?'Ausencia avisada y crédito generado.':'Ausencia avisada. Por horario de aviso no generó crédito automático.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos avisar la ausencia.')}finally{setBusy(false)}}
async function recover(cls:RecoveryClass){const credit=data?.credits.find(c=>c.status==='available');if(!credit){setError(true);setMessage('No tenés créditos disponibles para usar.');return}setBusy(true);setError(false);try{const r=await fetch('/api/portal/recoveries',{method:'POST',headers:auth(token),body:JSON.stringify({credit_id:credit.id,session_id:cls.id,notes:note})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setMessage('Recupero reservado y confirmado.');await load()}catch(e){setError(true);setMessage(e instanceof Error?e.message:'No pudimos reservar el recupero.')}finally{setBusy(false)}}
const calendar=useMemo(()=>{const days=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate();return Array.from({length:days},(_,i)=>{const date=`${period}-${String(i+1).padStart(2,'0')}`;return {date,my:data?.myClasses.filter(c=>c.date===date)||[],rec:data?.recoveryClasses.filter(c=>c.date===date&&c.available>0)||[]}})},[data,period]);
if(!token)return <main className="student-portal"><section className="student-shell login-shell"><p className="eyebrow">MUD ESPACIO</p><h1>Mi espacio.</h1><p>Entrá con el mail y la contraseña que te compartimos desde el taller para ver tus clases, avisar ausencias y tomar recuperos.</p>{message&&<p className={'feedback'+(error?' error':'')}>{message}</p>}<form className="admin-form compact-form portal-card" onSubmit={submitLogin}><label>Mail<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Contraseña<input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button className="button wide" disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form><a className="text-link" href="/">Volver al sitio</a></section></main>;
return <main className="student-portal"><section className="student-shell"><div className="portal-top"><div><p className="eyebrow">PORTAL ALUMNAS</p><h1>{data?.student.name||'Mi espacio'}</h1><p>Tu calendario de clases y recuperos disponibles.</p></div><button className="button secondary" onClick={()=>{localStorage.removeItem('mud_student_token');setToken('');setData(null)}}>Salir</button></div>{message&&<p className={'feedback'+(error?' error':'')}>{message}</p>}
<div className="student-dashboard"><aside><form className="portal-card admin-form compact-form" onSubmit={saveProfile}><div className="wide editor-heading"><div><p className="eyebrow">MI FICHA</p><h3>Datos básicos</h3></div></div><label>Nombre<input value={profile?.name||''} onChange={e=>setProfile(p=>p&&({...p,name:e.target.value}))}/></label><label>Mail<input disabled value={profile?.email||''}/></label><label>Contacto<input value={profile?.contact||''} onChange={e=>setProfile(p=>p&&({...p,contact:e.target.value}))}/></label><label>Instagram<input value={profile?.instagram||''} onChange={e=>setProfile(p=>p&&({...p,instagram:e.target.value}))}/></label><label className="wide">Notas<textarea rows={3} value={profile?.notes||''} onChange={e=>setProfile(p=>p&&({...p,notes:e.target.value}))}/></label><button className="button wide" disabled={busy}>Guardar ficha</button></form><div className="portal-card side-summary"><h3>Recuperos</h3><strong>{data?.credits.filter(c=>c.status==='available').length||0}</strong><p>crédito(s) disponibles</p>{data?.bookings.length?<div className="portal-mini-list">{data.bookings.map(b=><p key={b.id}>{b.class_date} · {b.schedule_label}</p>)}</div>:<p>Sin recuperos tomados este mes.</p>}</div></aside>
<section className="calendar-panel"><div className="calendar-head"><div><p className="eyebrow">CALENDARIO</p><h2>Clases y cupos</h2></div><input type="month" value={period} onChange={e=>{setPeriod(e.target.value);void load(token,e.target.value)}}/></div><div className="student-calendar">{calendar.map(d=><article key={d.date} className={(d.my.length||d.rec.length)?'has-events':''}><span>{Number(d.date.slice(8))}</span>{d.my.map(c=><button key={c.id} className={'class-pill own '+(c.attendance_status?'muted':'')} onClick={()=>setSelected(c)}>{c.start} propia{c.attendance_status?' · avisada':''}</button>)}{d.rec.slice(0,2).map(c=><button key={c.id} className="class-pill recovery" onClick={()=>setSelected(c)}>{c.start} recupero · {c.available}</button>)}</article>)}</div></section></div>
{selected&&<div className="portal-drawer"><div><p className="eyebrow">{('available'in selected)?'RECUPERO DISPONIBLE':'MI CLASE'}</p><h2>{selected.date} · {selected.start} a {selected.end}</h2><p>{selected.schedule_label}{selected.teacher_name?' · '+selected.teacher_name:''}</p>{'available'in selected?<><p>Hay {selected.available} cupo(s) disponibles para recuperar.</p><p className="portal-warning">Importante: al tomar un recupero se consume el crédito y no se puede cancelar desde el portal.</p></>:<><p>Si no venís, avisá desde acá. Si faltan 6 hs o más, se genera crédito automático.</p><p className="portal-warning">Importante: una vez enviada la falta no se puede cancelar desde el portal.</p></>}<label>Nota opcional<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="form-actions"><button className="button secondary" onClick={()=>setSelected(null)}>Cerrar</button>{'available'in selected?<button className="button" disabled={busy||!data?.credits.some(c=>c.status==='available')} onClick={()=>void recover(selected)}>Tomar recupero</button>:<button className="button" disabled={busy||!!selected.attendance_status} onClick={()=>void absence(selected)}>Avisar ausencia</button>}</div></div></div>}
</section></main>}
